version: '3.9'

services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: WalletDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ..   
      dockerfile: docker/Dockerfile 
    volumes:
      - ../scripts/wait-for-postgres.sh:/usr/local/bin/wait-for-postgres.sh    
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: WalletDB
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8080:8080"

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: tester
    volumes:
      - ../scripts/wait-for-postgres.sh:/usr/local/bin/wait-for-postgres.sh    
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: WalletDB
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:
